# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

domain: "###ZARF_VAR_DOMAIN###"

clustering:
  enabled: false

postgres:
  # Set to false to use external postgres
  internal: true
  selector:
    cluster-name: pg-cluster
  namespace: postgres
  port: 5432
  username: "jira"
  password: ""

sso:
  enabled: true
  # Options: "saml", "openid_connect"
  protocol: "saml"
  # This will replace the current list of default scopes.
  defaultClientScopes: []
  requiredGroups: []

setup:
  instanceDisplayName: "Jira Data Center"
  initialAdminSecret:
    name: jira-admin
    usernameKey: username
    passwordKey: password
    emailKey: email
    displayNameKey: displayName

jira:
  license:
    secretName: jira-license
    secretKey: license_key
    stringData:
      license_key: "AAAB4Q0ODAoPeNqVUk2P2jAUvOdXROqlVRUUB7JZkCx1CaZkC8luAogDFxMexAWcyHZg2V/ffICgZRepR4/tmTfz5ss4B/2Zch21dIQ6VqvTtHU3GuuWadmaK4AqlvIeVYBLxDCRgWxtyGLgEsbHDHy6A+wGoxEJXe9pqP1mgjZO92TJyt+Y+GMSvoReRDQ/3y1ABKuJBCGxgc5U5C1j4nilYxmoVZNlIl3msWqUB0OmK3WgAho0VmwPWIkctChfyFiwrBKrELKn25xezhVRwU5d4ApEDW5r6QGVCR65B7fvQtZ/d7+bi9n71DNnTh60vXCSKDLbPCXhoDn+NemSjVQTexC/Haf2epmz9uHnw+scz/HZidfDQ68XEd8YWqaD2s5j+56PSFFRTrSiW1k4AbEHUVB0iecYgdd/NUK/7RsW8rvaBo7TIrXSFHowTcd8bDaRthYAPEmzDMSd3F9yESdUwr+bvP5dRZMJJs+xEh//7eMDrY860IPLOp4Lt3p0cqt/LXeg10v4Nu/olz1pI8oKlFMe/38Zblp1Peh1U+5wfNKOc+KWFog15UzWrerBqrzVJ5zFqeBSc1OuCiVS2NhikS528Y9l/SY/PWnE6a4e4GbcCr2Z807CJ7UK/lzsD+lDVU4wLAIUDh8J3BnMCPGC9z4pMZxph+utjboCFDTa3S1umpcLoVwqWBI2JELm2ZTkX02mq"
    
# custom:
#    # Notice no `remoteGenerated`