# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

domain: "###ZARF_VAR_DOMAIN###"

clustering:
  enabled: false

postgres:
  # Set to false to use external postgres
  internal: true
  selector:
    cluster-name: pg-cluster
  namespace: postgres
  port: 5432
  username: "jira"
  password: ""

sso:
  enabled: true
  # Options: "saml", "openid_connect"
  protocol: "saml"
  # This will replace the current list of default scopes.
  defaultClientScopes: []
  requiredGroups: []

setup:
  # Admin user configuration
  admin:
    name: "admin"
    username: "admin"
    password: "admin"
    email: "admin@example.com"
    fullname: "Jira Administrator"

  # Setup job configuration
  job:
    image: registry.access.redhat.com/ubi9:9.4-1214.1726694543
    resources:
      requests:
        cpu: 2000m
        memory: 4Gi
      limits:
        cpu: 6
        memory: 6Gi
    backoffLimit: 6
    activeDeadlineSeconds: 600
    ttlSecondsAfterFinished: 100

jira:
  license:
    secretName: jira-license
    secretKey: license_key
    stringData:
      license_key: "###ZARF_VAR_LICENSE_KEY###"
