domain: "###ZARF_VAR_DOMAIN###"

postgres:
  # Set to false to use external postgres
  internal: true
  selector:
    cluster-name: pg-cluster
  namespace: postgres
  port: 5432
  username: "jira"
  password: ""

sso:
  enabled: true
  # Options: "saml", "openid_connect"
  protocol: "saml"

# custom:
#    # Notice no `remoteGenerated` field here on custom internal rule
#   - direction: Ingress
#     selector:
#       app: jenkins
#     remoteNamespace: jenkins
#     remoteSelector:
#       app: jenkins
#     port: 8180
#     description: "Ingress from Jenkins"
#   # No `remoteNamespace`, `remoteSelector`, or `port` fields on rule to `remoteGenerated`
#   - direction: Egress
#     selector:
#       app: webservice
#     remoteGenerated: Anywhere
#     description: "Egress from Mattermost"
