# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

database:
  type: postgres72  # https://atlassian.github.io/data-center-helm-charts/userguide/CONFIGURATION/#databasetype
  url: "jdbc:postgresql://###ZARF_VAR_JIRA_DB_ENDPOINT###:5432/###ZARF_VAR_JIRA_DB_NAME###"
  driver: org.postgresql.Driver
  credentials:
    secretName: jira-postgres
    usernameSecretKey: username
    passwordSecretKey: password

monitoring:
  exposeJmxMetrics: true
  jmxExporterInitContainer:
    runAsRoot: false

volumes:
  localHome:
    persistentVolumeClaim:
      create: true
      # storageClassName: your-storage-class-here
      resources:
        requests:
          storage: 10Gi
  sharedHome:
    persistentVolumeClaim:
      create: true
      accessModes:
        - ReadWriteOnce
    nfsPermissionFixer:
      enabled: false

ingress:
  nginx: false

jira:
  license:
    secretName: jira-license
    secretKey: license_key
  tomcatConfig:
    generateByHelm: true
  seraphConfig:
    generateByHelm: true
  resources:
    container:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "6"
        memory: "6Gi"
    jvm:
      maxHeap: "4g"
  securityContext:
    fsGroup: 2001
    runAsNonRoot: true
    runAsUser: 2001
    runAsGroup: 2001
  containerSecurityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsUser: 2001
    runAsGroup: 2001
  clustering:
    enabled: false
  service:
    annotations:
      traffic.sidecar.istio.io/excludeOutboundIPRanges: 10.43.60.232
    sessionAffinity: ClientIP
    sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 10800

replicaCount: 1

# This allows for clustering to work
podAnnotations:
  traffic.sidecar.istio.io/excludeOutboundPorts: 40001,40011
  traffic.sidecar.istio.io/excludeInboundPorts: 40001,40011

additionalEnvironmentVariables: []