ingress:
  nginx: false
proxyName: jira.###ZARF_VAR_DOMAIN###
domain: ###ZARF_VAR_DOMAIN###
jira:
  resources:
    container:
      requests:
        cpu: "100m"
        memory: "2Gi"
      limits:
        cpu: "10"
        memory: "6Gi"
    jvm:
      maxHeap: "4g"
  additionalEnvironmentVariables:
    - name: ATL_DB_TYPE
      value: "postgres72"
    - name: ATL_DB_DRIVER
      value: "org.postgresql.Driver"
    - name: ATL_JDBC_URL
      value: "jdbc:postgresql://###ZARF_VAR_JIRA_DB_ENDPOINT###:5432/###ZARF_VAR_JIRA_DB_NAME###"
    - name: ATL_JDBC_USER
      value: ###ZARF_VAR_JIRA_DB_USERNAME###
    - name: ATL_JDBC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "jira-postgres"
          key: "password"
volumes:
  localHome:
    persistentVolumeClaim:
      create: true
      # storageClassName: your-storage-class-here
      resources:
        requests:
          storage: 1Gi
  sharedHome:
    nfsPermissionFixer:
      enabled: false
# When istio injected, add an annotation with the istio version to the manager pods only
# podAnnotations:
#   bigbang.dev/istioVersion: ###ZARF_VAR_ISTIO_VERSION###
# networkPolicies:
#   enabled: true
#   ingressLabels:
#     app: tenant-ingressgateway
#   controlPlaneCidr: 0.0.0.0/0

commonLabels:
  uds/user: "1001"
  uds/group: "0"
