# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{ if .Values.clustering.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: jira-destination-rule-clustering
spec:
  host: jira.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          # set a new session cookie with istio per atlassian guidelines: https://confluence.atlassian.com/enterprise/jira-data-center-load-balancer-examples-781200827.html
          # note: this cookie is explicitly different than JSESSIONID, let jira handle that
          name: JIRACONSISTENTHASH
          path: /
          ttl: 300m

{{ end }}
