{{- if .Values.setup.createSecrets }}
apiVersion: batch/v1
kind: Job
metadata:
  name: jira-setup
spec:
  backoffLimit: {{ .Values.setup.job.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.setup.job.activeDeadlineSeconds }}
  ttlSecondsAfterFinished: {{ .Values.setup.job.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        app: jira
        component: setup
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-jira
          image: {{ .Values.setup.job.image }}
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting 60 seconds for Jira to become responsive..."
              sleep 60
              until curl -sk https://jira.uds.dev/status | tee /dev/stderr | grep -q '"state":"FIRST_RUN"'; do
                echo "Waiting for Jira to be ready..."
                sleep 10
              done
              sleep 90
              echo "Proceeding with setup..."
      containers:
        - name: setup
          image: {{ .Values.setup.job.image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -ex
              dnf install -y --allowerasing python3 python3-pip curl
              
              # Create and activate virtual environment
              python3 -m venv /setup/venv
              source /setup/venv/bin/activate
              
              # Install packages in the virtual environment
              pip install --no-cache-dir requests beautifulsoup4
              
              # Make venv accessible to main container
              chmod -R 755 /setup/venv            
              source /setup/venv/bin/activate
              python3 /scripts/test_license.py
          env:
            - name: JIRA_DOMAIN
              value: "jira.uds.dev"
            - name: JIRA_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: jira-admin
                  key: username
            - name: JIRA_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jira-admin
                  key: password
            - name: JIRA_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: jira-admin
                  key: email
            - name: JIRA_ADMIN_FULLNAME
              valueFrom:
                secretKeyRef:
                  name: jira-admin
                  key: fullname
            - name: JIRA_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: jira-license
                  key: license-key
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: script
              mountPath: /scripts
              readOnly: true
            - name: setup
              mountPath: /setup
      volumes:
        - name: script
          configMap:
            name: jira-setup-script
            defaultMode: 0755
        - name: setup
          emptyDir: {}
{{- end }} 