{{- if ne .Values.postgres.password "" }}
apiVersion: v1
kind: Secret
metadata:
  name: jira-postgres
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/opaque
stringData:
  username: {{ .Values.postgres.username }}
  password: {{ .Values.postgres.password }}
{{- end }}
