apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: jira
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.sso }}
  sso:
    - name: Jira Login
      clientId: uds-package-jira
      redirectUris:
        - "https://jira.{{ .Values.domain }}/plugins/servlet/oidc/callback"
  {{- end }}
  network:
    expose:
      - service: jira
        podLabels:
          app.kubernetes.io/name: jira
        gateway: tenant
        host: jira
        port: 80
        targetPort: 8080
    allow:
      - direction: Egress
        podLabels:
          app.kubernetes.io/name: jira
        remoteGenerated: Anywhere

# Custom rules for unanticipated scenarios
      {{- range .Values.custom }}
      - direction: {{ .direction }}
        selector:
          {{ .selector | toYaml | nindent 10 }}
        {{- if not .remoteGenerated }}
        remoteNamespace: {{ .remoteNamespace }}
        remoteSelector:
          {{ .remoteSelector | toYaml | nindent 10 }}
        port: {{ .port }}
        {{- else }}
        remoteGenerated: {{ .remoteGenerated }}
        {{- end }}
        description: {{ .description }}
      {{- end }}