apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: jira
  namespace: {{ .Release.Namespace }}
spec:
  network:
    expose:
      - service: jira
        podLabels:
          app.kubernetes.io/name: jira
        gateway: tenant
        host: jira
        port: 80
        targetPort: 8080
    allow:
      - direction: Egress
        podLabels:
          app.kubernetes.io/name: jira
        remoteGenerated: Anywhere
