tasks:
  - name: create
    description: Create the Dev Dependency Zarf Packages
    inputs:
      options:
        description: For setting create time variables and flags
      architecture:
        description: The architecture of the package to create
        default: ${UDS_ARCH}
    actions:
      - cmd: ./uds zarf package create src/wait/ --confirm --no-progress --architecture=${{ .inputs.architecture }} --skip-sbom ${{ .inputs.options }}
      - cmd: ./uds zarf package create src/namespace/ --confirm --no-progress --architecture=${{ .inputs.architecture }} --skip-sbom ${{ .inputs.options }}
