# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tasks:
  - name: all
    actions:
      - task: health-check
      - task: ingress

  - name: health-check
    actions:
      - description: Jira StatefulSet Health Check
        wait:
          cluster:
            kind: StatefulSet
            name: jira
            namespace: jira

  - name: ingress
    actions:
      - description: Jira UI Health Check
        wait:
          network:
            protocol: https
            address: jira.uds.dev
            code: 200
