# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tasks:
  - name: all
    actions:
      - task: health-check
      - task: ingress
      - task: create-project

  - name: health-check
    actions:
      - description: Jira StatefulSet Health Check
        wait:
          cluster:
            kind: StatefulSet
            name: jira
            namespace: jira

  - name: ingress
    actions:
      - description: Jira UI Health Check
        wait:
          network:
            protocol: https
            address: jira.uds.dev
            code: 200

  - name: create-project
    description: Create a project in Jira
    actions:
      - cmd: |
          docker run --rm --ipc=host --net=host --mount type=bind,source="$(pwd)",target=/tests mcr.microsoft.com/playwright:v1.49.1-jammy sh -c " \
            cd tests && \
            npm ci && \
            npx playwright test \
            "
        dir: tests