tasks:
  - name: health-check
    actions:
      - description: Jira StatefulSet Health Check
        wait:
          cluster:
            kind: StatefulSet
            name: jira
            namespace: jira

  - name: ingress
    actions:
      - description: Jira UI Health Check
        wait:
          network:
            protocol: https
            address: jira.uds.dev/secure/SetupApplicationProperties!default.jspa
            code: 200
