# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tasks:
  - name: all
    actions:
      - task: health-check
      - task: ui

  - name: health-check
    actions:
      - description: Jira StatefulSet Health Check
        wait:
          cluster:
            kind: StatefulSet
            name: jira
            namespace: jira

  - name: ui
    actions:
      - cmd: |
          docker run --user="$(id -u)" --rm --ipc=host --net=host --mount type=bind,source="$(pwd)",target=/app mcr.microsoft.com/playwright:v1.54.2-jammy sh -c " \
            export npm_config_cache=/tmp/.npm && \
            cd app && \
            npm ci && \
            npx playwright test \
            "
        dir: tests
