# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tasks:
  - name: all
    actions:
      - task: health-check
      - task: ingress

  - name: health-check
    actions:
      - description: Jira StatefulSet Health Check
        wait:
          cluster:
            kind: StatefulSet
            name: jira
            namespace: jira

  - name: ingress
    actions:
      - description: Jira UI Health Check
        wait:
          network:
            protocol: https
            address: jira.uds.dev
            code: 200

  - name: ui
    description: Jira UI Checks
    actions:
      - cmd: |
          docker run --rm --ipc=host --net=host --mount type=bind,source="$(pwd)",target=/app mcr.microsoft.com/playwright:v1.47.2-jammy sh -c " \
            cd app && \
            npm ci && \
            npx playwright test \
            "
        dir: tests