# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

variables:
  jira:
    jira_db_endpoint: "pg-cluster.postgres.svc.cluster.local"
    LICENSE_KEY: ""
  postgres-operator:
    postgresql:
      enabled: true  # Set to false to not create the PostgreSQL resource
      teamId: "uds"
      volume:
        size: "10Gi"
      numberOfInstances: 2
      users:
        jira.jira: []  # database owner
      databases:
        jiradb: jira.jira
      version: "13"
      ingress:
        remoteGenerated: Anywhere
