# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: PR Title Check

on:
  # This workflow is triggered on pull requests to the main branch.
  pull_request:
    branches: [main]
    # milestoned is added here so that a PR can be re-triggered if it is milestoned.
    types: [milestoned, opened, edited, synchronize]

jobs:
  run:
    uses: defenseunicorns/uds-common/.github/workflows/callable-commitlint.yaml@16464ce560d1a1423d4ddcf4961bc0354964f785 # v1.15.2
