# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Release

on:
  push:
    branches:
      - main

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.
  packages: read # Allows reading the content of the repository's packages.
  id-token: write

jobs:
  tag-new-version:
    permissions: write-all
    runs-on: uds-marketplace-ubuntu-big-boy-4-core
    outputs:
      release_created: ${{ steps.release-flag.outputs.release_created }}
    steps:
      - name: Create Release Tag
        id: tag
        uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
      - id: release-flag
        run: echo "release_created=${{ steps.tag.outputs.release_created || false }}" >> "$GITHUB_OUTPUT"

  publish:
    permissions:
      contents: write # Allows reading the content of the repository.
      packages: write # Allows reading the content of the repository's packages.
      id-token: write
    needs: tag-new-version
    if: ${{ needs.tag-new-version.outputs.release_created == 'true' }}
    strategy:
      matrix:
        flavor: [upstream, registry1]
        architecture: [amd64]
    uses: defenseunicorns/uds-common/.github/workflows/callable-publish.yaml@90ea06c9746a21fbff8867b1421ac13072b6a12b # v1.6.1
    with:
      flavor: ${{ matrix.flavor }}
      runsOn: uds-marketplace-ubuntu-big-boy-8-core
    secrets: inherit # Inherits all secrets from the parent workflow.
