# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Scorecards supply-chain security
on:
  # Only the default branch is supported.
  branch_protection_rule:
  schedule:
    - cron: '30 1 * * 6'
  push:
    branches: ["main"]

# Declare default permissions as read only.
permissions: read-all

jobs:
  validate:
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      # Used to receive a badge.
      id-token: write
    uses: defenseunicorns/uds-common/.github/workflows/callable-scorecard.yaml@22be0673a01c1b8b00a0c9a3eb00f1bd618963a3 # v1.6.3
    secrets: inherit
